version: "3.1"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  msg-queue:
    image: redis
    ports:
      - 6379:6379

  adminer:
    image: adminer
    ports:
      - 8080:8080
